name: Main

on:
  push:
    branches: [ "main" ]
  
jobs:
  build_and_tests:
    name: Test sync
    secrets: inherit
    with:
      go_version: ${{ vars.GO_VERSION }}
    uses: ./.github/workflows/w_tests.yml

  build-artifacts:
    name: Artifacts
    needs: build_and_tests
    uses: ./.github/workflows/w_artifacts.yml
    secrets: inherit
    with:
      os: '["linux", "windows", "macos"]'
      architectures: '["amd64", "arm64"]'
      go_version: ${{ vars.GO_VERSION }}

