name: Release
# This workflow is triggered when a new tag is published
# `git tag v0.0.1alpha`
# `git push --tags`
# If the tag already exists, use this commanf to delete it `git tag -d v0.0.1alpha`
on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
    build_and_tests:
      name: Test sync
      secrets: inherit
      with:
        go_version: ${{ vars.GO_VERSION }}
      uses: ./.github/workflows/w_tests.yml

    release:
      if: contains(github.ref, 'tags/v')
      runs-on: ubuntu-latest
      needs: build_and_tests
      outputs: 
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        v_num:  ${{ steps.version.outputs.number }}
    
      steps:
        - uses: actions/checkout@v3
        - name: Get version number
          id: version
          run: |
            echo "number=$(echo '${{ github.ref }}' | cut -d '/' -f 3)" >>${GITHUB_OUTPUT}
        - name: Show version number
          run: |
            echo ${{ steps.version.outputs.number }}
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body_path: file_rename/CHANGELOG.md
            draft: false
            prerelease: true   
        
    build-artifacts:
      name: Artifacts
      needs: release
      uses: ./.github/workflows/w_artifacts.yml
      secrets: inherit
      with:
        os: '["linux", "windows", "macos"]'
        architectures: '["amd64","arm64"]'
        go_version: ${{ vars.GO_VERSION }}
        release: -${{ needs.release.outputs.v_num }}
        release_url: ${{ needs.release.outputs.upload_url }}
